### ISSUE TITLE
Unable to install Node-feature-discovery using operator

### ISSUE THREAD

**Issue by bitvijays** [kubernetes-sigs/node-feature-discovery-operator#106]
Dear NFD operator team,

Hope you are doing well. Thank you for your support and creating an operator for NFD. Much appreciated. We tried installing NFD using operator and faced few issues. Details below:

**What happened**:

Tried to install Node-feature-discovery-operator using Instructions provided at [OperatorHub nfd-operator](https://operatorhub.io/operator/nfd-operator)

**What you expected to happen**:

Install NFD using operator

**How to reproduce it (as minimally and precisely as possible)**:

Follow instructions on OperatorHub for ndf-operator on a fresh Kubernetes install

![image](https://user-images.githubusercontent.com/9039339/146107558-505d3c09-53ab-464c-96a3-d2e7a1492221.png)

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/9039339/146107675-df0c83bf-fb08-4fc6-9cf2-8b453b55e130.png)

`kubectl describe pods -n operators`

![image](https://user-images.githubusercontent.com/9039339/146107753-147fce5e-533d-43e3-b9cd-96dd62817401.png)

**Environment**:
- Kubernetes version (use `kubectl version`): `1.21.7`

Further notes:

- Reading the GitHub Wiki, it seems that current version of `nfd-operator` is `0.3` 
- We were able to install NFD using [node-feature-discovery](https://github.com/kubernetes-sigs/node-feature-discovery)
- Probably, we just need to update operatorhub?

**Comment by marquiz** [comment]
Hmm, I don't think this nfd deployment, even if the ClusterServiceVersion status shows installing/failed. The operator still is running ok and doing it's job even if the readiness probe fails. Very confusing, though 😬 

Any comments @ArangoGutierrez? Has this readiness probe been around in OLM for how long? Could be somehow fix this for older releases in operatorhub, e.g. requiring an older version of olm? I think we should add `operator-sdk-ready` in our Dockerfile

**Comment by ArangoGutierrez** [comment]
we have dropped v0,2 from the catalog https://github.com/k8s-operatorhub/community-operators/tree/main/operators/nfd-operator
could you check if v0.3 works? @bitvijays

**Comment by marquiz** [comment]
I think it should work. I think I tested v0.3 and it worked

**Comment by ArangoGutierrez** [comment]
Feel free to close this issue @bitvijays after testing :)

**Comment by ArangoGutierrez** [comment]
we are past more than 3 versions since this post was filed, I am closing for now
/close
