### ISSUE TITLE
Update operand to v0.10.0

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#107]
**What would you like to be added**:

Support NFD [v0.10.0](https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.10.0)

In addition to bumping the image version e.g. topology-updater should be supported.

**Why is this needed**:

I want the latest and greatest

**Comment by ArangoGutierrez** [comment]
1. https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/115

**Comment by ArangoGutierrez** [comment]
2- https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/117

**Comment by ArangoGutierrez** [comment]
master is now V0.10 compatible 
V0.4.0 will be also v0.10 compatible
/close
