### ISSUE TITLE
Add a way to request worker-one-shot to the operator

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery-operator#121]
For specific use cases, not having the worker nodes running there as daemonset is wanted, find out the best way to request the worker-one-shot command from the operator 

### NFD-Worker oneshot

The `-oneshot` flag causes nfd-worker to exit after one pass of feature
detection.

Default: *false*

Example:

```bash
nfd-worker -oneshot -no-publish
```

**Comment by ArangoGutierrez** [comment]
Maybe a boolean var on the CR? 
and extra CR just for this?

**Comment by marquiz** [comment]
On top of my head, a separate boolean variable would sound better. Most of the parameters should be the same with the daemonset so a separate crd sounds like unneeded extra maintenance burden, too.

The method to re-trigger would be to delete and re-create the CR?

**Comment by ArangoGutierrez** [comment]
what about splitting the master deployment from the workers, then a second way to define worker deployment, that way we provide more control over:

- How users deploy masters and service
- diff worker-conf
- one-shot
- prune labels

**Comment by ArangoGutierrez** [comment]
> set for V0.5.0

**Comment by marquiz** [comment]
> what about splitting the master deployment from the workers,

You mean in terms of a separate CRD? Maybe that could bring some benefit. There are risks too, though, e.g. version skew between worker and master.
