### ISSUE TITLE
Support HELM chart deployment

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery-operator#174]
Currently there is no official HELM chart for the operator, making the only official way of deployment the operator-hub/operator-sdk.
Moving forward we should also support HELM as a way for deploying the operator.

- [x] https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/175
- [x] https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/177
- [x] [Add Helm charts ](https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/179)
- [x] [Host a Helm repo for the charts](https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/185)
- [x] [Add documentation ](https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/186)

**Comment by ArangoGutierrez** [comment]
- [x] https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/175
- [ ] https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/177
- [ ] Add Helm charts

**Comment by marquiz** [comment]
Any progress on this @ArangoGutierrez ?

**Comment by ArangoGutierrez** [comment]
Been busy with the GPU-O release, but next week I have some room for this

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/185

**Comment by ArangoGutierrez** [comment]
Code completed
/Close
