### ISSUE TITLE
immutable nfd-worker config

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery-operator#18]
the reconciler resets my changes to nfd-worker `ConfigMap`. How do I deploy the operator from operatorhub but add my own nfd-worker.conf?

**Comment by ArangoGutierrez** [comment]
Heya @mythi could you test #36 and comment if it fixes this issue, thanks!

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/39
