### ISSUE TITLE
Operand configurability

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#19]
A meta-issue (inspired by #18) where I tried to collect things that should be configurable. The mechanism to use would be the operand CRD.

Master:
- [ ] mTLS configuration 
  - [ ] `--ca-file`, `--cert-file` and `--key-file`
  - [ ] `--verify-node-name`
- [ ] `--extra-label-ns`
- [ ] `--resource-labels`
- [ ] support `--prune` in some way to help with un-installation??

Worker:
- [ ] mTLS configuration via `--ca-file`, `--cert-file` and `--key-file`
- [x] user-specified worker config through ConfigMap (#18, #36)
- [x] `--sleep-interval`

**Comment by mythi** [comment]
I think many of these could be covered by supporting configurable args for both master and worker:

```
type NodeFeatureDiscoverySpec struct {
	OperandNamespace    string `json:"operandNamespace"`
	OperandImage             string `json:"operandImage"`
        OperandMasterArgs     []string `json:"operandMasterArgs"`
        OperandWorkerArgs     []string `json:"operandWorkerArgs"`

}
```

Perhaps TLS should be managed by cert-manager?

**Comment by marquiz** [comment]
> I think many of these could be covered by supporting configurable args for both master and worker:

Sure, they're just hard to verify and so easy to mess up. I don't know if this is a usual pattern in the "operator world", though. I don't think it would be much harder to add separate fields for the important command line flags. Maybe the args could be a first aid, though and useful in debugging or very exotic use cases(?)



> Perhaps TLS should be managed by cert-manager?

Yes it *should*, there's even an issue about that but I haven't had bandwidth for that.

**Comment by ArangoGutierrez** [comment]
sorry for that, testing some prow things for this repo

**Comment by ArangoGutierrez** [comment]
#36 will address `user-specified worker config through ConfigMap `
