### ISSUE TITLE
Manager Container: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by pjconnol** [kubernetes-sigs/node-feature-discovery-operator#197]
**What happened**: When deploying the v0.6.0 `nfd-controller-manager` pod, it reports a status `CreateContainerConfigError`. Running describe on the failing pod, it reports the following:
```
Error: container has runAsNonRoot and image will run as root (pod: "nfd-controller-manager-5c9f974d55-5hcmz_node-feature-discovery-operator(a137aedd-6e47-4175-8082-adb77c78840d)", container: manager)
```
It seems that the `registry.k8s.io/nfd/node-feature-discovery-operator:v0.6.0-minimal` is still running as root which the `runAsNonRoot: true` securityContext spec disagrees with but I'm not entirely sure as it seems that you are setting the USER privileges in the [Dockerfile](https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/master/Dockerfile#L36)

**What you expected to happen**: The manager container should start without any issues regarding `runAsNonRoot` parameter

**How to reproduce it (as minimally and precisely as possible)**:
Download the source for NFD Operator:

```bash
git clone -b v0.6.0 https://github.com/kubernetes-sigs/node-feature-discovery-operator
cd node-feature-discovery-operator/
```

Install dependencies:

```bash
apt install make
# Install Go
wget https://go.dev/dl/go1.20.5.linux-amd64.tar.gz &&  rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.5.linux-amd64.tar.gz
echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile
export PATH=$PATH:/usr/local/go/bin
```

Deploy the operator, using the following command:

```bash
make deploy
```

Create a NodeFeatureDiscovery instance:

```bash
kubectl apply -f config/samples/nfd.kubernetes.io_v1_nodefeaturediscovery.yaml
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.26.3
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`): Ubuntu 22.04
- Install tools: make

**Comment by marquiz** [comment]
Thanks for reporting this @pjconnol. Looks like the [Dockerfile of v0.6.0](https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/v0.6.0/Dockerfile) is borken as we don't set the user for the minimal image.

ping @ArangoGutierrez. I think we'd need to backport relevant bits from #193 and cut v0.6.1. Or then do v0.7.0
