### ISSUE TITLE
Support NFD v0.16

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#199]
**What would you like to be added**:

The operator should play nicely with the latest features in the operand. E.g. (some of these might be no-issues already)

- [x] nfd-gc #201 
- [x] Tolerations on NFD CR #203
- [ ] nfd-master
  - [ ] leader election in case of HA (if NodeFeature API is enabled)
  - [ ] config file support
  - [x] no need to create service if NodeFeature API is enabled #202 
- [ ] metrics (do we want/need some new options wrt this?)
- [ ] topology-updater
  - [ ] `-pods-fingerprint` 
- [ ] nfd-gc

**Why is this needed**:

Keep up with the operand

**Comment by ArangoGutierrez** [comment]
[ ] Tolerations  on NFD CR

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/203

**Comment by marquiz** [comment]
Added nfd-gc to the checklist in the description, need to think what else is missing

**Comment by ArangoGutierrez** [comment]
We now have V0.16 with more features and a new CRD
