### ISSUE TITLE
Supporting taints via NFD operator

### ISSUE THREAD

**Issue by yevgeny-shnaidman** [kubernetes-sigs/node-feature-discovery-operator#239]
Taints are specified in the NodeRules objects, and are applied by master pod.  This may cause the NFD worker pods on the tainted nodes to become unscheduled, since NFD operator is not aware of the NodeRules and is not updating the worker daemonsets with appropriate tolerations.
The possible solution is to create additional controller in the operator, that will watch for NodeRules creation. In case NodeRule contains taint definition, the controller will kick off reconcilation of the nodefeaturediscovery controller, which will check the presence of the taints in any existing NodeRule and will update the worker daemonset accordingly. 
The new controller will have to watch for Create and Update events, but not for Delete events, since there is no problem for worker to be running with additional tolerations
Reconciliation kick-off can be achieved by applying an annotation to the NFD CR. We can agree on a specific naming , and the value of the annotation will be increased subsequently with each time the reconciliation loop needs to be restarted

**Comment by marquiz** [comment]
This would be very nice feature, making tainting a lot more user-friendly.

**Comment by yevgeny-shnaidman** [comment]
We will start working on it once we finish with the refactoring
