### ISSUE TITLE
Enhance nfd-worker placement

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery-operator#29]
**What would you like to be added**:
enable NFD operator to deploy nfd-worker pods on nodes labeled other than "node-role.kubernetes.io/worker"

**Why is this needed**:

Current implementation of the NFD-operator create a daemonset which is only taking nodes with "node-role.kubernetes.io/worker" into accout. Kubernetes deployments without this label on non-master nodes won't see nfd-worker scheduled.

**Comment by marquiz** [comment]
I left this same comment in #31: Do we really need some affinity setting? Daemonset should be scheduled on on every schedulable node, shoudln't it(?)
