### ISSUE TITLE
Run nfd-master as Deployment

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#4]
Run nfd-master as Deployment instead of a DaemonSet, similar what the [NFD upstream deployment template](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/nfd-master.yaml.template) does.

Makes it possible to deploy NFD in managed clusters which have no master nodes.

**Comment by ArangoGutierrez** [comment]
My concern with this concept is that worker nodes could tag them selves as Masters and gain privileges on the system. How could we avoid that on a Vanilla Kubernetes deployment?

**Comment by marquiz** [comment]
How would a Deployment be different in terms of privileges??

**Comment by ArangoGutierrez** [comment]
From the issue init comment "clusters which have no master nodes." , then a Deployment will create masters and a way to create labels without controlling the head of the cluster. I may be wrong tho, not a security expert by no means, I keep my password on a post-it. but I think is something worth double checking before going into that direction

**Comment by marquiz** [comment]
Master nodes and nfd-master are a different/separate thing. When you run nfd-master it doesn't label the node it's running on as a master node. You need to run nfd-master somewhere in the cluster (in order for NFD to be able to work i.e. create node labels). If there are no master nodes in the cluster you'll end up with a non-working state when using a DaemonSet.

Nevertheless, the thinking behind running nfd-master on master node(s) by default was still security. Nfd-master would be "safer" there because master nodes are unlinkely to run any user workloads. In any case, I think the operator should take the "masterless" cluster into consideration, only use Deployment in that case or smth.

**Comment by marquiz** [comment]
Still valid
/remove-lifecycle stale

**Comment by ArangoGutierrez** [comment]
@zvonkok I would like to get your eyes on this issue
