### ISSUE TITLE
Operatorhub should be updated 

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#48]
**What would you like to be added**:

NFD-operator page in operatorhub (https://operatorhub.io/operator/nfd-operator) still points to release 0.1.0. Should be 0.2.0.

**Why is this needed**:

Need to stay up-to-date

**Comment by ArangoGutierrez** [comment]
Good catch

**Comment by ArangoGutierrez** [comment]
upstream-community-operators [O] nfd-operator (0.1.0 0.2.0) operator-framework/community-operators#3270 was merged
/close
