### ISSUE TITLE
nfs-worker pod is CrashLoopBack with connection refused error

### ISSUE THREAD

**Issue by rupang790** [kubernetes-sigs/node-feature-discovery-operator#51]
On my K8s cluster , I tried to install nfs-operator by manual deploy.( clone and make)
But it seems not installed correctly because of ofd-worker pod. 

My cluster information as below:
- Container Runtime : CRI-O
- Kubernetes version : v.1.20.0
- Cluster Apiserver IPs : 192.168.2.0/24
- Pod Cidr IPs : 10.244.0.0/16
- Pod CNI : Calico

<img width="981" alt="image" src="https://user-images.githubusercontent.com/40801176/112807004-5afc6180-90b2-11eb-9d02-803570e64fb7.png">

1. According to results of ```kubectl get pods --all-namespaces -o wide```, nfd-operator and nfd-master get correct pod cidr IP address but nfd-worker is not. How I can solve this?
2. nfs-worker pod keep showing error as below and I think it is because of IP address, is it correct? 
```
2021/03/29 08:08:05 WARNING: ignoring kconfig option 'ARCH_HWEIGHT_CFLAGS': value exceeds max length of 63 characters
2021/03/29 08:08:05 Node Feature Discovery Worker v0.7.0
2021/03/29 08:08:05 NodeName: 'k8s-worker01'
INFO: 2021/03/29 08:08:05 parsed scheme: ""
INFO: 2021/03/29 08:08:05 scheme "" not registered, fallback to default scheme
INFO: 2021/03/29 08:08:05 ccResolverWrapper: sending update to cc: {[{nfd-master:12000  <nil> 0 <nil>}] <nil> <nil>}
INFO: 2021/03/29 08:08:05 ClientConn switching balancer to "pick_first"
WARNING: 2021/03/29 08:08:10 grpc: addrConn.createTransport failed to connect to {nfd-master:12000  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup nfd-master on 10.96.0.10:53: read udp 192.168.2.33:33535->10.96.0.10:53: read: connection refused". Reconnecting...
WARNING: 2021/03/29 08:08:21 grpc: addrConn.createTransport failed to connect to {nfd-master:12000  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup nfd-master on 10.96.0.10:53: read udp 192.168.2.33:60792->10.96.0.10:53: i/o timeout". Reconnecting...
WARNING: 2021/03/29 08:08:28 grpc: addrConn.createTransport failed to connect to {nfd-master:12000  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup nfd-master on 10.96.0.10:53: read udp 192.168.2.33:33733->10.96.0.10:53: read: connection refused". Reconnecting...
WARNING: 2021/03/29 08:08:35 grpc: addrConn.createTransport failed to connect to {nfd-master:12000  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup nfd-master on 10.96.0.10:53: read udp 192.168.2.33:53327->10.96.0.10:53: read: connection refused". Reconnecting...
```

**Comment by marquiz** [comment]
Thanks for the report @rupang790.

The problem is probably because of `hostNetwork: true` in the worker spec. #52 should fix that. @rupang790 could you try that out and report back?

**Comment by marquiz** [comment]
@rupang790 #52 was merged. Could you test with latest master and report back?

**Comment by rupang790** [comment]
@marquiz, Sorry for late reply. I was busy with other issues.
I will try again and report back.

**Comment by rupang790** [comment]
@marquiz, I solve this to "make image" again, tagging to my registry and push, pull on worker manually before the deploy. 
Also I use v0.8.0 of nfs-master/worker, then NFD has been working well. Thanks for fix and help. :)
