### ISSUE TITLE
Should the Operator be NameSpaced or Cluster

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery-operator#54]
Per definition
>When you create a new CustomResourceDefinition (CRD), the Kubernetes API Server creates a new RESTful resource path for each version you specify. The CRD can be either namespaced or cluster-scoped, as specified in the CRD's scope field. As with existing built-in objects, deleting a namespace deletes all custom objects in that namespace. CustomResourceDefinitions themselves are non-namespaced and are available to all namespaces.

currently the operator runs namespaced, what do we think about it being Cluster-scoped?

**Comment by mythi** [comment]
> what do we think about it being Cluster-scoped?

`Node` objects are non-namespaced too so I think a cluster scoped NFD CRD would be better aligned with that.

**Comment by marquiz** [comment]
> > what do we think about it being Cluster-scoped?
> 
> `Node` objects are non-namespaced too so I think a cluster scoped NFD CRD would be better aligned with that.

Hmm, now thinking of this, I'm not really sure 🙃 Node objects sure are non-namespaced but OTOH the operator always runs in some namespace. I'd probably stay with namespaced. Makes cleaning up kind of easier: deleting the namespace should make sure that no old configs haunt you in the future. Thoughts? @zvonkok?

**Comment by mythi** [comment]
With namespaced CRDs the operator needs to watch all those namespaces to CRUD an NFD instance in each of them. What I've understood and it was also mentioned by @zvonkok in https://github.com/kubernetes-sigs/node-feature-discovery/issues/508#issuecomment-814909667 that one instance of NFD in a cluster is preferred. AFAIU with that it would be simpler to watch cluster-scoped CRDs. Alternatively, the operator could watch only one namespace (`WATCH_NAMESPACE`?) but it'd still be possible to create orphan CRDs...

**Comment by zwpaper** [comment]
as NFD support the [instance flag](https://kubernetes-sigs.github.io/node-feature-discovery/v0.8/advanced/master-commandline-reference.html#-instance), we may run multiple instance of NFD, it should be reasonable to be namespaced.

for example, we may leave different people managing their features and isolated by both label namespace and k8s namespaces, eg. gpu-nfd for nvidia.com under gpu-ops ns, network-nfd for network.example.com network-ops ns.

/remove-lifecycle stale
