### ISSUE TITLE
User guideline documentation

### ISSUE THREAD

**Issue by courtneypacheco** [kubernetes-sigs/node-feature-discovery-operator#65]
**What would you like to be added**:
User guidelines documentation

**Why is this needed**:
Similar to what I propose in my issue #64 , I think user guideline documentation would be a great feature too. And again, I'm already going to go through the process of ramping up, so I figure I might as well add this feature too.

Thoughts?

**Comment by ArangoGutierrez** [comment]
Any updates on this @vaibhav2107 ?
