### ISSUE TITLE
Support additional custom source configurations

### ISSUE THREAD

**Issue by slintes** [kubernetes-sigs/node-feature-discovery-operator#66]
**What would you like to be added**:
[Recently](https://github.com/kubernetes-sigs/node-feature-discovery/pull/429) configuration options for the NFD worker were extended: it supports a `/etc/kubernetes/node-feature-discovery/custom.d` directory now, which can be used for additional custom source configurations besides those in the main worker config. Typically this directory will be populated by mounting ConfigMaps. The needed volume and mount configurations should be handled by the operator.

**Why is this needed**:
The new configuration option allows dynamic configuration by potentially multiple parties. Each party can maintain their own ConfigMap without the need for cross party agreements. Ideally the operator can watch for those ConfigMaps and reconfigure the worker on the fly by adding and removing relevant volumes and mounts.

**Design considerations**
The big question is: how to find the relevant ConfigMaps. Some thoughts:

- add the ConfigMap names to the NFD CRD. This makes implementation easy. But this isn't very dynamic and still needs manual work, which introduces some risk that in case of misconfiguration (name mismatch between config and actual ConfigMap, accidental deletion of ConfigMaps, ...?) the nfd workers won't start because a volume mounts fails.
- let the operator find relevant ConfigMaps and (re)-configure the worker daemonset dynamically. However, we still need to know which ConfigMaps are relevant. The first restriction is easy: the CM needs to be in the same namespace as the NFD CR / worker. And then? A very basic check might be to have a look into the data and try to parse it as custom source configuration. Or at least look for e.g. the "matchOn" string. An alternative might be to require the ConfigMaps to have a certain name, e.g. a "custom-config-" prefix (maybe configurable in the NFD CR), or a label, or an annotation.
- what worries me a bit: for this dynamic solution the operator would need to watch for all ConfigMaps in all namespaces. At least I did not find how to dynamically restrict the watch to the desired namespace(s). Is this a problem (thinking of huge clusters with many CMs...)?
- side note: talking about namespaces: do I see correct that the operator watches ALL namespaces for NFD CRs and potentially installs multiple instances of NFD in multiple namespaces? Is that on purpose?

I think my favorite is using a marker label for ConfigMaps which should be mounted.
When we agree a way forward, I volunteer to implement it, in order to finish the work which started on the NFD worker :) 

Related: https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/53

**Comment by mythi** [comment]
> side note: talking about namespaces: do I see correct that the operator watches ALL namespaces for NFD CRs and potentially installs multiple instances of NFD in multiple namespaces? Is that on purpose?

your observation is correct, see #54

**Comment by slintes** [comment]
> in case of misconfiguration (name mismatch between config and actual ConfigMap, accidental deletion of ConfigMaps, ...?) the nfd workers won't start because a volume mounts fails.

I learned there is a `optional` flag for configmap mounts, so this isn't an issue

**Comment by marquiz** [comment]
Let's not close this yet
/remove-lifecycle stale

**Comment by marquiz** [comment]
Hmm, do we still want to keep this open? Especially after [NFD v0.10.0](https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.10.0) (and [#653](https://github.com/kubernetes-sigs/node-feature-discovery/pull/653))? I'd say no.

If we would implement this it would probably mean a separate CRD for the extra custom configs which doesn't make much sense after https://github.com/kubernetes-sigs/node-feature-discovery/pull/653, in practice overlapping functionality and more maintenance burden

Thoughts @slintes @ArangoGutierrez?

**Comment by slintes** [comment]
thanks for the heads up

>  in practice overlapping functionality and more maintenance burden

sounds like a good argument to me to close this

**Comment by ArangoGutierrez** [comment]
Let's close this after https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/119

**Comment by marquiz** [comment]
> Let's close this after #119

Agree
