### ISSUE TITLE
Change image repo to k8s.gcr.io/nfd/node-feature-discovery

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#9]
Start to use the new community-hosted image repository. Operator configuration needs to be changed as we do not have the `:latest` tag there.

**Comment by ArangoGutierrez** [comment]
What about https://quay.io/repository/kubernetes_incubator/node-feature-discovery-operator ??

**Comment by marquiz** [comment]
Hmm, what about that(?) 😄 How's that related?

**Comment by ArangoGutierrez** [comment]
that we have a quay hosted image repo, are you proposing moving it to the k8s community one?

**Comment by marquiz** [comment]
This issue is about the operand image repo. And I think it was actually fixed by #12 
/close

Please re-open if that's not the case.

About the operator repo we have #1

**Comment by ArangoGutierrez** [comment]
Operand/Operator... ;)
