### ISSUE TITLE
Link not working in Advanced section

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes-sigs/node-feature-discovery-operator#94]
In https://kubernetes-sigs.github.io/node-feature-discovery-operator/v0.2/advanced/nodefeaturediscovery.html
`For more information about how to setup the WorkerConfig stanza, see worker config reference`, the link is giving 404 Error.

I think there might be some version problem in the redirected link.

**Comment by vaibhav2107** [comment]
@Evalle 
I think you can change that in file `nodefeaturediscovery.md` placed under the docs section (docs -> advanced).

**Comment by Evalle** [comment]
On `nodefeaturediscovery.md` file the link builds via 
```
https://kubernetes-sigs.github.io/node-feature-discovery/{{site.operand_version}}/advanced/worker-configuration-reference.html)
```
note `{{site.operand_version}}`.

I found only `operand_version` variable in the repository, which has `v0.8` value (https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/master/docs/_config.yml#L56) not v0.7 or v0.2. 
Am I missing something? Thanks!

**Comment by Evalle** [comment]
@vaibhav2107 any feedback on this ^ Thanks!
